name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: generate image tag
      run: |
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV


    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/tomposgergo2/k8s-cicd-13c:$IMAGE_TAG        
        docker login ghcr.io -u tomposgergo2 -p ${{ secrets.GHCR_TOKEN }}
        docker push ghcr.io/tomposgergo2/k8s-cicd-13c:$IMAGE_TAG

#TODO:
# - kubectl apply futtatása
#     - config: secretbe el kell tenni: base64-ben
# deployment.yaml-ban az image tag frissítése